### ISSUE TITLE
I get a continuous error on console F8 when I die

### ISSUE THREAD

**Issue by SATTAGAMES** [TheIndra55/fivem-burglary#2] opened 2019-05-02 18:16 UTC
I get a continuous error on console F8 when I die
Could you help me with this error?
The job is running fine off this error in the console

http://prntscr.com/njm95q

**Comment by TheIndra55** [comment] 2019-05-13 07:56
Couldn't reproduce this on a local server, might need to test with more people for this

**Comment by tymaan** [comment] 2019-06-22 23:40
Getting the same console error. Losing about 16fps from resource warning whenever you die

**Comment by tymaan** [comment] 2019-06-30 17:23
`		-- cancel mission if player is dead
		if IsPedDeadOrDying(PlayerPedId()) and onMission then
			TriggerServerEvent("burglary:ended", true, false)
			
			ForceEndMission()
		end`



gameplay/busted.lua    this solves that issua

**Comment by TheIndra55** [comment] 2019-07-04 10:30
Thanks @tymaan i'll look into it later today

**Comment by TheIndra55** [comment] 2019-12-31 09:02
Fixed as of #6

**Closed by TheIndra55** 2019-12-31 09:02 UTC
